title: GenAI Code Labs
author: GenAI Learner
logo: ""

execute:
  execute_notebooks: "off"   # set to "auto" when ready to run on build

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist

html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""
